//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TroubleshootProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TroubleshootProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum
        ///Titanium
        ///DEXcam 1-4
        ///DEXcam 4HD
        ///CariVu
        ///GXS-700
        ///KaVo IXS
        ///Other.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size=10
        ///Family=Consolas.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentrix
        ///Eaglesoft
        ///OpenDental
        ///PracticeWorks
        ///SoftDent
        ///Other
        ///N/A.
        /// </summary>
        internal static string PMSVersions {
            get {
                return ResourceManager.GetString("PMSVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.5.0
        ///9.4.8
        ///9.4.5
        ///9.4.4
        ///9.4.3
        ///9.4.2
        ///9.3.x
        ///9.2.x
        ///9.1.x
        ///9.0.x
        ///10.1.6
        ///10.1.2
        ///10.1.1
        ///10.1.0
        ///10.0.x
        ///3rd Party Imaging
        ///N/A (Transfer/How-to).
        /// </summary>
        internal static string SwVersions {
            get {
                return ResourceManager.GetString("SwVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.8
        ///1.0.7
        ///1.0.6
        ///1.0.5
        ///1.0.4
        ///1.0.3
        ///1.0.2.
        /// </summary>
        internal static string TitaniumVersions {
            get {
                return ResourceManager.GetString("TitaniumVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP
        ///Vista
        ///7
        ///8/8.1
        ///10
        ///Server 2003
        ///Server 2008
        ///Server 2012
        ///Server 2016
        ///Server 2019.
        /// </summary>
        internal static string WindowsVersions {
            get {
                return ResourceManager.GetString("WindowsVersions", resourceCulture);
            }
        }
    }
}
